#!/command/with-contenv bash

source /assets/functions/00-container
source /assets/functions/20-discourse
prepare_service
PROCESS_NAME="discourse"

bootstrap_filesystem
configure_git_safe_directory
configure_discourse
custom_files /app/
custom_scripts
configure_plugins
configure_test_plugins
setup_shell
migrate_db
compile_assets
configure_notification_email
create_admin_user
install_themes
configure_theme_permissions_and_settings
chown discourse:discourse /app

liftoff
